name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-15]
        xcode: ['16.4']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
    
    - name: Show Xcode version
      run: xcodebuild -version
    
    - name: Install xcpretty
      run: gem install xcpretty
    
    - name: Build App (Debug)
      run: |
        xcodebuild -project DarkModeSwitch.xcodeproj \
          -scheme App \
          -configuration Debug \
          -derivedDataPath .build \
          CODE_SIGNING_ALLOWED=NO \
          build \
          | xcpretty

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-15]
        xcode: ['16.4']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
    
    - name: Show Xcode version
      run: xcodebuild -version

    - name: Test with Coverage
      run: |
        xcodebuild -workspace DarkModeSwitch.xcworkspace \
          -scheme Tests \
          -testPlan UnitTests \
          -configuration Debug \
          -derivedDataPath .build \
          -enableCodeCoverage YES \
          CODE_SIGNING_ALLOWED=NO \
          test

    - name: Generate code coverage
      run: ./scripts/generate-coverage.sh .build

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        slug: Matejkob/macos-dark-mode-switch
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage_report.lcov
        fail_ci_if_error: false